### ISSUE TITLE
Failing on `bundle exec knife cook vagrant@chef_cap_demo`

### ISSUE THREAD

**Issue by michaelachrisco** [smartlogic/chef-cap-demo#1]
I went through the following steps and had an issue:

``` bash
bundle exec knife cook vagrant@chef_cap_demo
...
Reading package lists...
[2015-03-25T23:10:41+00:00] INFO: execute[apt-get update] ran successfully
[2015-03-25T23:10:41+00:00] INFO: Processing package[postgresql-client] action install (postgresql::client line 32)
[2015-03-25T23:10:45+00:00] INFO: Processing package[libpq-dev] action install (postgresql::client line 32)
[2015-03-25T23:10:50+00:00] INFO: Processing chef_gem[pg] action install (postgresql::ruby line 57)

================================================================================
Error executing action `install` on resource 'chef_gem[pg]'
================================================================================

Gem::Installer::ExtensionBuildError
-----------------------------------
ERROR: Failed to build gem native extension.

        /opt/chef/embedded/bin/ruby extconf.rb
checking for pg_config... yes
Using config values from /usr/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... no
checking for PQconnectdb() in -llibpq... no
checking for PQconnectdb() in -lms/libpq... no
Can't find the PostgreSQL client library (libpq)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/opt/chef/embedded/bin/ruby
    --with-pg
    --without-pg
    --enable-windows-cross
    --disable-windows-cross
    --with-pg-config
    --without-pg-config
    --with-pg_config
    --without-pg_config
    --with-pg-dir
    --without-pg-dir
    --with-pg-include
    --without-pg-include=${pg-dir}/include
    --with-pg-lib
    --without-pg-lib=${pg-dir}/lib
    --with-pqlib
    --without-pqlib
    --with-libpqlib
    --without-libpqlib
    --with-ms/libpqlib
    --without-ms/libpqlib


Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.18.1 for inspection.
Results logged to /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.18.1/ext/gem_make.out

Cookbook Trace:
---------------
/tmp/chef-solo/cookbooks/postgresql/recipes/ruby.rb:57:in `rescue in from_file'
/tmp/chef-solo/cookbooks/postgresql/recipes/ruby.rb:24:in `from_file'
/tmp/chef-solo/cookbooks/chef_cap/recipes/database.rb:1:in `from_file'
/tmp/chef-solo/cookbooks/chef_cap/recipes/default.rb:50:in `from_file'

Resource Declaration:
---------------------
# In /tmp/chef-solo/cookbooks/postgresql/recipes/ruby.rb

 57:     chef_gem "pg"
 58:   rescue Gem::Installer::ExtensionBuildError => e

Compiled Resource:
------------------
# Declared in /tmp/chef-solo/cookbooks/postgresql/recipes/ruby.rb:57:in `rescue in from_file'

chef_gem("pg") do
  provider Chef::Provider::Package::Rubygems
  action :install
  retries 0
  retry_delay 2
  package_name "pg"
  version "0.18.1"
  cookbook_name :postgresql
  recipe_name "ruby"
end

[2015-03-25T23:10:57+00:00] WARN: Failed to properly build pg gem. Forcing properly linking and retrying (omnibus fix)
[2015-03-25T23:10:57+00:00] INFO: Processing execute[generate pg gem Makefile] action run (postgresql::ruby line 88)
```

``` Ruby
ssh -l deploy chef_cap_demo
Permission denied (publickey,password).
```

**Comment by michaelachrisco** [comment]
I am running mac os 10.10, not sure if that matters.

**Comment by danivovich** [comment]
@michaelachrisco Thanks for checking this out. This is pretty out of date now. I'll try and get it updated to work with the latest version of Chef and Ubuntu so that it is a more realistic example again. Sorry you had trouble with it. These things tend to get stale, unfortunately.
